// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bitbucket.org/edts/go-task-management/internal/model"
)

type AssignTaskInput struct {
	ID         string  `json:"id"`
	AssignedTo *string `json:"assignedTo,omitempty"`
}

type AssignUserToTeamInput struct {
	TeamID string   `json:"teamId"`
	UserID []string `json:"userId"`
}

type AssignedUsers struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type AuthResponse struct {
	Token        string      `json:"token"`
	RefreshToken string      `json:"refreshToken"`
	User         *model.User `json:"user"`
}

type CreateTaskInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	Status      string  `json:"status"`
	AssignedTo  *string `json:"assignedTo,omitempty"`
	TeamID      string  `json:"teamId"`
	DueDate     string  `json:"dueDate"`
}

type CreateTeamInput struct {
	Name        string   `json:"name"`
	Description *string  `json:"description,omitempty"`
	Assignee    []string `json:"assignee,omitempty"`
}

type CreateUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type DeletedTaskNotification struct {
	TaskID  string `json:"taskId"`
	Deleted bool   `json:"deleted"`
}

type LoginUserInput struct {
	Email    *string `json:"email,omitempty"`
	Password string  `json:"password"`
}

type MoveTaskInput struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

type Mutation struct {
}

type Query struct {
}

type RefreshTokenInput struct {
	RefreshToken string `json:"refreshToken"`
}

type Subscription struct {
}

type TeamSummary struct {
	Team        *model.Team `json:"team"`
	MemberCount *int32      `json:"memberCount,omitempty"`
}

type UpdateTaskInput struct {
	ID          string  `json:"id"`
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Status      *string `json:"status,omitempty"`
	AssignedTo  *string `json:"assignedTo,omitempty"`
	DueDate     *string `json:"dueDate,omitempty"`
}

type UpdateTeamInput struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description *string  `json:"description,omitempty"`
	Assignee    []string `json:"assignee,omitempty"`
}
